#cloud-config

# Note: This code has been tested on Ubuntu 24.04 LTS (Nobel Numbat) and will not work on other Linux distros

cloud_config_modules:
  - apt_configure
  - package_update_upgrade_install

bootcmd:
  - test -d /etc/apt/keyrings || install -m 0755 -d /etc/apt/keyrings
  - test -f /etc/apt/keyrings/hashicorp-archive-keyring.gpg || (wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /etc/apt/keyrings/hashicorp-archive-keyring.gpg && chmod a+r /etc/apt/keyrings/hashicorp-archive-keyring.gpg)
  - test -f /etc/apt/keyrings/microsoft.gpg || (curl -sLS https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/keyrings/microsoft.gpg && chmod go+r /etc/apt/keyrings/microsoft.gpg)

apt:
  sources:
    azure-cli:
      source: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ $RELEASE main'
      filename: azure-cli.list
    powershell:
      source: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/24.04/prod $RELEASE main'
      filename: microsoft-prod.list
    terraform:
      source: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $RELEASE main'
      filename: hashicorp.list

package_update: true

packages:
  - azure-cli
  - dnsutils
  - jp
  - openvpn
  - powershell
  - python3-pip
  - terraform

package_upgrade: true

package_reboot_if_required: true

write_files:
  - path: /etc/environment
    content: |
      ARM_USE_MSI=true
      ARM_TENANT_ID=${aad_tenant_id}
    append: true
