#cloud-config

# Note: This code has been tested on Ubuntu 24.04 LTS (Nobel Numbat) and will not work on other Linux distros

cloud_config_modules:
  - apt_configure
  - package_update_upgrade_install

bootcmd:
  - test -d /etc/apt/keyrings || install -m 0755 -d /etc/apt/keyrings
  - test -f /etc/apt/keyrings/docker.asc || (curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc && chmod a+r /etc/apt/keyrings/docker.asc)
  - test -f /etc/apt/keyrings/hashicorp-archive-keyring.gpg || (wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /etc/apt/keyrings/hashicorp-archive-keyring.gpg && chmod a+r /etc/apt/keyrings/hashicorp-archive-keyring.gpg)
  - test -f /etc/apt/keyrings/helm.gpg || (curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey | gpg --dearmor | sudo tee /etc/apt/keyrings/helm.gpg && chmod a+r /etc/apt/keyrings/helm.gpg)
  - test -f /etc/apt/keyrings/microsoft.gpg || (curl -sLS https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/keyrings/microsoft.gpg && chmod go+r /etc/apt/keyrings/microsoft.gpg)

apt:
  sources:
    azure-cli:
      source: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ $RELEASE main'
      filename: azure-cli.list
    docker:
      source: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $RELEASE stable'
      filename: docker.list
    helm:
      source: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main'
      filename: helm-stable-debian.list
    powershell:
      source: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/24.04/prod $RELEASE main'
      filename: microsoft-prod.list
    terraform:
      source: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $RELEASE main'
      filename: hashicorp.list
  
package_update: true

packages:
  - autofs
  - azure-cli
  - cifs-utils
  - containerd.io
  - docker-buildx-plugin
  - docker-ce
  - docker-ce-cli
  - docker-compose-plugin
  - helm
  - jp
  - keyutils
  - krb5-config
  - krb5-user
  - libnss-winbind
  - libpam-winbind
  - notary
  - ntp
  - powershell
  - python3-pip
  - samba
  - terraform
  - winbind

package_upgrade: true

package_reboot_if_required: true

write_files:
  - content: |
      network: {config: disabled}
    path: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
  - content: |
      {
        "adds_domain_name": "${adds_domain_name}",
        "dns_server": "${dns_server}",
        "key_vault_name": "${key_vault_name}",
        "storage_account_name": "${storage_account_name}",
        "storage_share_name": "${storage_share_name}"
      }
    path: /etc/azuresandbox-conf.json
    permissions: '0644'
